# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: Web # In a different organization
    type: git
    name: TrainingProject/Web
  - repository: MyGitHubRepo
    type: github
    endpoint: Github2 #Service connection
    name: JeaustinRodriguez/Checkout-task
    ref: main

pool:
  vmImage: windows-latest

steps:
- checkout: Web
- checkout: self
- checkout: MyGitHubRepo
- script: dir $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'